version '3.2'

services:
  fpm:
    image: gianiaz/test-code

  nginx:
    image: gianiaz/test-code-nginx
    depends_on:
      - fpm

  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=phantom
      - MYSQL_USER=phantom
      - MYSQL_PASSWORD=phantom
