version: '3.2'

services:

  fpm:
    image: gianiaz/test-code

  nginx:
    image: gianiaz/test-code-nginx
    depends_on:
      - fpm
      - mysql

  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  yarn:
    image: node:8-alpine
    working_dir: /var/www/gianiaz
    volumes:
      - .:/var/www/gianiaz
    environment:
      YARN_CACHE_FOLDER: /var/www/gianiaz/var/cache/yarn
    command: ['yarn', 'install']
